feature:
  sample_value: True
  source: True
  non_null_count: True
  unique_count: True
  dtype: True
  unique_val_list: True

parameters:
  unique_val_length: 15

data:
  paths:
  separator: ";"

db:
  sql_alchemy_connection_string: postgresql://username:password@domain:5432/db
  schema: public
  row_limit: 10
  table_names: