name: datadictionary
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - numpy=1.20.3
  - pandas=1.2.4
  - pip=21.1.2
  - pip:
      - python-box==5.3.0
      - coloredlogs==15.0.1
      - PyYAML==5.4.1
      - openpyxl==3.0.7
      - SQLAlchemy==1.4.22
      - psycopg2-binary==2.9.1